/* 
 * Automated Music Promoter
 *
 * acba automated music promoter
 *
 * OpenAPI spec version: 2.0
 * Contact: support@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// StoredProcedureRequest
    /// </summary>
    [DataContract]
    public partial class StoredProcedureRequest :  IEquatable<StoredProcedureRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StoredProcedureRequest" /> class.
        /// </summary>
        /// <param name="_Params">Optional array of input and output parameters..</param>
        /// <param name="Schema">Schema.</param>
        /// <param name="Wrapper">Add this wrapper around the expected data set before returning, same as URL parameter..</param>
        /// <param name="Returns">If returning a single value, use this to set the type of that value, same as URL parameter..</param>
        public StoredProcedureRequest(List<StoredProcedureParam> _Params = default(List<StoredProcedureParam>), StoredProcedureResultSchema Schema = default(StoredProcedureResultSchema), string Wrapper = default(string), string Returns = default(string))
        {
            this._Params = _Params;
            this.Schema = Schema;
            this.Wrapper = Wrapper;
            this.Returns = Returns;
        }
        
        /// <summary>
        /// Optional array of input and output parameters.
        /// </summary>
        /// <value>Optional array of input and output parameters.</value>
        [DataMember(Name="params", EmitDefaultValue=false)]
        public List<StoredProcedureParam> _Params { get; set; }

        /// <summary>
        /// Gets or Sets Schema
        /// </summary>
        [DataMember(Name="schema", EmitDefaultValue=false)]
        public StoredProcedureResultSchema Schema { get; set; }

        /// <summary>
        /// Add this wrapper around the expected data set before returning, same as URL parameter.
        /// </summary>
        /// <value>Add this wrapper around the expected data set before returning, same as URL parameter.</value>
        [DataMember(Name="wrapper", EmitDefaultValue=false)]
        public string Wrapper { get; set; }

        /// <summary>
        /// If returning a single value, use this to set the type of that value, same as URL parameter.
        /// </summary>
        /// <value>If returning a single value, use this to set the type of that value, same as URL parameter.</value>
        [DataMember(Name="returns", EmitDefaultValue=false)]
        public string Returns { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StoredProcedureRequest {\n");
            sb.Append("  _Params: ").Append(_Params).Append("\n");
            sb.Append("  Schema: ").Append(Schema).Append("\n");
            sb.Append("  Wrapper: ").Append(Wrapper).Append("\n");
            sb.Append("  Returns: ").Append(Returns).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as StoredProcedureRequest);
        }

        /// <summary>
        /// Returns true if StoredProcedureRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of StoredProcedureRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StoredProcedureRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this._Params == other._Params ||
                    this._Params != null &&
                    this._Params.SequenceEqual(other._Params)
                ) && 
                (
                    this.Schema == other.Schema ||
                    this.Schema != null &&
                    this.Schema.Equals(other.Schema)
                ) && 
                (
                    this.Wrapper == other.Wrapper ||
                    this.Wrapper != null &&
                    this.Wrapper.Equals(other.Wrapper)
                ) && 
                (
                    this.Returns == other.Returns ||
                    this.Returns != null &&
                    this.Returns.Equals(other.Returns)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this._Params != null)
                    hash = hash * 59 + this._Params.GetHashCode();
                if (this.Schema != null)
                    hash = hash * 59 + this.Schema.GetHashCode();
                if (this.Wrapper != null)
                    hash = hash * 59 + this.Wrapper.GetHashCode();
                if (this.Returns != null)
                    hash = hash * 59 + this.Returns.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
