/* 
 * Automated Music Promoter
 *
 * acba automated music promoter
 *
 * OpenAPI spec version: 2.0
 * Contact: support@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// StoredFunctionResponse
    /// </summary>
    [DataContract]
    public partial class StoredFunctionResponse :  IEquatable<StoredFunctionResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StoredFunctionResponse" /> class.
        /// </summary>
        /// <param name="OutParamName_">Name and value of any given output parameter..</param>
        public StoredFunctionResponse(string OutParamName_ = default(string))
        {
            this.OutParamName_ = OutParamName_;
        }
        
        /// <summary>
        /// Name and value of any given output parameter.
        /// </summary>
        /// <value>Name and value of any given output parameter.</value>
        [DataMember(Name="_out_param_name_", EmitDefaultValue=false)]
        public string OutParamName_ { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StoredFunctionResponse {\n");
            sb.Append("  OutParamName_: ").Append(OutParamName_).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as StoredFunctionResponse);
        }

        /// <summary>
        /// Returns true if StoredFunctionResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of StoredFunctionResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StoredFunctionResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.OutParamName_ == other.OutParamName_ ||
                    this.OutParamName_ != null &&
                    this.OutParamName_.Equals(other.OutParamName_)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.OutParamName_ != null)
                    hash = hash * 59 + this.OutParamName_.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
