/* 
 * Automated Music Promoter
 *
 * acba automated music promoter
 *
 * OpenAPI spec version: 2.0
 * Contact: support@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FieldSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FieldSchemaTests
    {
        // TODO uncomment below to declare an instance variable for FieldSchema
        //private FieldSchema instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FieldSchema
            //instance = new FieldSchema();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FieldSchema
        /// </summary>
        [Test]
        public void FieldSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FieldSchema
            //Assert.IsInstanceOfType<FieldSchema> (instance, "variable 'instance' is a FieldSchema");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'DbType'
        /// </summary>
        [Test]
        public void DbTypeTest()
        {
            // TODO unit test for the property 'DbType'
        }
        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Test]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }
        /// <summary>
        /// Test the property 'Precision'
        /// </summary>
        [Test]
        public void PrecisionTest()
        {
            // TODO unit test for the property 'Precision'
        }
        /// <summary>
        /// Test the property 'Scale'
        /// </summary>
        [Test]
        public void ScaleTest()
        {
            // TODO unit test for the property 'Scale'
        }
        /// <summary>
        /// Test the property 'DefaultValue'
        /// </summary>
        [Test]
        public void DefaultValueTest()
        {
            // TODO unit test for the property 'DefaultValue'
        }
        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [Test]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }
        /// <summary>
        /// Test the property 'AllowNull'
        /// </summary>
        [Test]
        public void AllowNullTest()
        {
            // TODO unit test for the property 'AllowNull'
        }
        /// <summary>
        /// Test the property 'FixedLength'
        /// </summary>
        [Test]
        public void FixedLengthTest()
        {
            // TODO unit test for the property 'FixedLength'
        }
        /// <summary>
        /// Test the property 'SupportsMultibyte'
        /// </summary>
        [Test]
        public void SupportsMultibyteTest()
        {
            // TODO unit test for the property 'SupportsMultibyte'
        }
        /// <summary>
        /// Test the property 'AutoIncrement'
        /// </summary>
        [Test]
        public void AutoIncrementTest()
        {
            // TODO unit test for the property 'AutoIncrement'
        }
        /// <summary>
        /// Test the property 'IsPrimaryKey'
        /// </summary>
        [Test]
        public void IsPrimaryKeyTest()
        {
            // TODO unit test for the property 'IsPrimaryKey'
        }
        /// <summary>
        /// Test the property 'IsForeignKey'
        /// </summary>
        [Test]
        public void IsForeignKeyTest()
        {
            // TODO unit test for the property 'IsForeignKey'
        }
        /// <summary>
        /// Test the property 'RefTable'
        /// </summary>
        [Test]
        public void RefTableTest()
        {
            // TODO unit test for the property 'RefTable'
        }
        /// <summary>
        /// Test the property 'RefField'
        /// </summary>
        [Test]
        public void RefFieldTest()
        {
            // TODO unit test for the property 'RefField'
        }
        /// <summary>
        /// Test the property 'Validation'
        /// </summary>
        [Test]
        public void ValidationTest()
        {
            // TODO unit test for the property 'Validation'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
