/* 
 * Automated Music Promoter
 *
 * acba automated music promoter
 *
 * OpenAPI spec version: 2.0
 * Contact: support@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RelationshipSchemas
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RelationshipSchemasTests
    {
        // TODO uncomment below to declare an instance variable for RelationshipSchemas
        //private RelationshipSchemas instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RelationshipSchemas
            //instance = new RelationshipSchemas();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RelationshipSchemas
        /// </summary>
        [Test]
        public void RelationshipSchemasInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RelationshipSchemas
            //Assert.IsInstanceOfType<RelationshipSchemas> (instance, "variable 'instance' is a RelationshipSchemas");
        }

        /// <summary>
        /// Test the property 'Resource'
        /// </summary>
        [Test]
        public void ResourceTest()
        {
            // TODO unit test for the property 'Resource'
        }

    }

}
