/* 
 * Automated Music Promoter
 *
 * acba automated music promoter
 *
 * OpenAPI spec version: 2.0
 * Contact: support@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RelationshipSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RelationshipSchemaTests
    {
        // TODO uncomment below to declare an instance variable for RelationshipSchema
        //private RelationshipSchema instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RelationshipSchema
            //instance = new RelationshipSchema();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RelationshipSchema
        /// </summary>
        [Test]
        public void RelationshipSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RelationshipSchema
            //Assert.IsInstanceOfType<RelationshipSchema> (instance, "variable 'instance' is a RelationshipSchema");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Alias'
        /// </summary>
        [Test]
        public void AliasTest()
        {
            // TODO unit test for the property 'Alias'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Test]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }
        /// <summary>
        /// Test the property 'RefTable'
        /// </summary>
        [Test]
        public void RefTableTest()
        {
            // TODO unit test for the property 'RefTable'
        }
        /// <summary>
        /// Test the property 'RefField'
        /// </summary>
        [Test]
        public void RefFieldTest()
        {
            // TODO unit test for the property 'RefField'
        }
        /// <summary>
        /// Test the property 'JunctionTable'
        /// </summary>
        [Test]
        public void JunctionTableTest()
        {
            // TODO unit test for the property 'JunctionTable'
        }
        /// <summary>
        /// Test the property 'JunctionField'
        /// </summary>
        [Test]
        public void JunctionFieldTest()
        {
            // TODO unit test for the property 'JunctionField'
        }
        /// <summary>
        /// Test the property 'JunctionRefField'
        /// </summary>
        [Test]
        public void JunctionRefFieldTest()
        {
            // TODO unit test for the property 'JunctionRefField'
        }
        /// <summary>
        /// Test the property 'AlwaysFetch'
        /// </summary>
        [Test]
        public void AlwaysFetchTest()
        {
            // TODO unit test for the property 'AlwaysFetch'
        }

    }

}
