/* 
 * Automated Music Promoter
 *
 * acba automated music promoter
 *
 * OpenAPI spec version: 2.0
 * Contact: support@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StoredRoutineSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StoredRoutineSchemaTests
    {
        // TODO uncomment below to declare an instance variable for StoredRoutineSchema
        //private StoredRoutineSchema instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StoredRoutineSchema
            //instance = new StoredRoutineSchema();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StoredRoutineSchema
        /// </summary>
        [Test]
        public void StoredRoutineSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StoredRoutineSchema
            //Assert.IsInstanceOfType<StoredRoutineSchema> (instance, "variable 'instance' is a StoredRoutineSchema");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ReturnType'
        /// </summary>
        [Test]
        public void ReturnTypeTest()
        {
            // TODO unit test for the property 'ReturnType'
        }
        /// <summary>
        /// Test the property 'ReturnSchema'
        /// </summary>
        [Test]
        public void ReturnSchemaTest()
        {
            // TODO unit test for the property 'ReturnSchema'
        }
        /// <summary>
        /// Test the property '_Params'
        /// </summary>
        [Test]
        public void _ParamsTest()
        {
            // TODO unit test for the property '_Params'
        }

    }

}
