/* 
 * Automated Music Promoter
 *
 * acba automated music promoter
 *
 * OpenAPI spec version: 2.0
 * Contact: support@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StoredFunctionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StoredFunctionResponseTests
    {
        // TODO uncomment below to declare an instance variable for StoredFunctionResponse
        //private StoredFunctionResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StoredFunctionResponse
            //instance = new StoredFunctionResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StoredFunctionResponse
        /// </summary>
        [Test]
        public void StoredFunctionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StoredFunctionResponse
            //Assert.IsInstanceOfType<StoredFunctionResponse> (instance, "variable 'instance' is a StoredFunctionResponse");
        }

        /// <summary>
        /// Test the property 'OutParamName_'
        /// </summary>
        [Test]
        public void OutParamName_Test()
        {
            // TODO unit test for the property 'OutParamName_'
        }

    }

}
