/* 
 * Automated Music Promoter
 *
 * acba automated music promoter
 *
 * OpenAPI spec version: 2.0
 * Contact: support@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StoredRoutineSchemas
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StoredRoutineSchemasTests
    {
        // TODO uncomment below to declare an instance variable for StoredRoutineSchemas
        //private StoredRoutineSchemas instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StoredRoutineSchemas
            //instance = new StoredRoutineSchemas();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StoredRoutineSchemas
        /// </summary>
        [Test]
        public void StoredRoutineSchemasInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StoredRoutineSchemas
            //Assert.IsInstanceOfType<StoredRoutineSchemas> (instance, "variable 'instance' is a StoredRoutineSchemas");
        }

        /// <summary>
        /// Test the property 'Resource'
        /// </summary>
        [Test]
        public void ResourceTest()
        {
            // TODO unit test for the property 'Resource'
        }

    }

}
