/* 
 * Automated Music Promoter
 *
 * acba automated music promoter
 *
 * OpenAPI spec version: 2.0
 * Contact: support@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StoredFunctionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StoredFunctionRequestTests
    {
        // TODO uncomment below to declare an instance variable for StoredFunctionRequest
        //private StoredFunctionRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StoredFunctionRequest
            //instance = new StoredFunctionRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StoredFunctionRequest
        /// </summary>
        [Test]
        public void StoredFunctionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StoredFunctionRequest
            //Assert.IsInstanceOfType<StoredFunctionRequest> (instance, "variable 'instance' is a StoredFunctionRequest");
        }

        /// <summary>
        /// Test the property '_Params'
        /// </summary>
        [Test]
        public void _ParamsTest()
        {
            // TODO unit test for the property '_Params'
        }
        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Test]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }
        /// <summary>
        /// Test the property 'Returns'
        /// </summary>
        [Test]
        public void ReturnsTest()
        {
            // TODO unit test for the property 'Returns'
        }

    }

}
