/* 
 * Automated Music Promoter
 *
 * acba automated music promoter
 *
 * OpenAPI spec version: 2.0
 * Contact: support@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StoredRoutineParameterSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StoredRoutineParameterSchemaTests
    {
        // TODO uncomment below to declare an instance variable for StoredRoutineParameterSchema
        //private StoredRoutineParameterSchema instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StoredRoutineParameterSchema
            //instance = new StoredRoutineParameterSchema();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StoredRoutineParameterSchema
        /// </summary>
        [Test]
        public void StoredRoutineParameterSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StoredRoutineParameterSchema
            //Assert.IsInstanceOfType<StoredRoutineParameterSchema> (instance, "variable 'instance' is a StoredRoutineParameterSchema");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'ParamType'
        /// </summary>
        [Test]
        public void ParamTypeTest()
        {
            // TODO unit test for the property 'ParamType'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'DbType'
        /// </summary>
        [Test]
        public void DbTypeTest()
        {
            // TODO unit test for the property 'DbType'
        }
        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Test]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }
        /// <summary>
        /// Test the property 'Precision'
        /// </summary>
        [Test]
        public void PrecisionTest()
        {
            // TODO unit test for the property 'Precision'
        }
        /// <summary>
        /// Test the property 'Scale'
        /// </summary>
        [Test]
        public void ScaleTest()
        {
            // TODO unit test for the property 'Scale'
        }
        /// <summary>
        /// Test the property '_Default'
        /// </summary>
        [Test]
        public void _DefaultTest()
        {
            // TODO unit test for the property '_Default'
        }

    }

}
