/* 
 * Automated Music Promoter
 *
 * acba automated music promoter
 *
 * OpenAPI spec version: 2.0
 * Contact: support@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TableSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TableSchemaTests
    {
        // TODO uncomment below to declare an instance variable for TableSchema
        //private TableSchema instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TableSchema
            //instance = new TableSchema();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TableSchema
        /// </summary>
        [Test]
        public void TableSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TableSchema
            //Assert.IsInstanceOfType<TableSchema> (instance, "variable 'instance' is a TableSchema");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'Plural'
        /// </summary>
        [Test]
        public void PluralTest()
        {
            // TODO unit test for the property 'Plural'
        }
        /// <summary>
        /// Test the property 'PrimaryKey'
        /// </summary>
        [Test]
        public void PrimaryKeyTest()
        {
            // TODO unit test for the property 'PrimaryKey'
        }
        /// <summary>
        /// Test the property 'NameField'
        /// </summary>
        [Test]
        public void NameFieldTest()
        {
            // TODO unit test for the property 'NameField'
        }
        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Test]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }
        /// <summary>
        /// Test the property 'Related'
        /// </summary>
        [Test]
        public void RelatedTest()
        {
            // TODO unit test for the property 'Related'
        }

    }

}
